### ISSUE TITLE
v0.1.0 Roadmap

### ISSUE THREAD

**Issue by kawinie** [OPEnSLab-OSU/eDNA-Interface#4]
High-level overview of functionalities to be implemented for v0.1.0 release.

- [x] General status update via polling
- [x] Status update for valve overview
- [x] Task creation
- [x] State timeline update 
- [x] Form validation for task submission
- [x] Task submission
